name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: ⚙️ Install Dependencies
        run: yarn

      - name: 🏗️ Build
        run: yarn build

      - name: 🧪 Test
        run: |
          yarn lint
          yarn test:coverage
        env:
          CI: true

      - name: 🔭 e2e
        run: |
          yarn run link
          mkdir -p /tmp/e2e-project/src;
          echo "export type Test = { test: string; };" > /tmp/e2e-project/src/index.ts;

          cd /tmp/e2e-project;

          yarn init --yes;
          yarn add --dev typescript;
          yarn tsc --init;
          yarn add --dev @ts-dev-tools/core;
          yarn link @ts-dev-tools/core;

          sudo chmod +x node_modules/.bin/ts-dev-tools
          yarn ts-dev-tools install;

          yarn lint;
          yarn tsc src/*.ts;

      - name: 📊 Code coverage
        uses: codecov/codecov-action@v1
